# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]

path: ../datasets/  # dataset root dir
train: train_log_noise/  # train images (relative to 'path') 4 images
val: valid_log_noise/  # val images (relative to 'path') 4 images
test:  test_log_noise/

# Keypoints
kpt_shape: [7, 2]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)

# Classes dictionary
names:
  0: ER